# MySQL ??
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tourism?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: "000000"
        driver-class-name: com.mysql.cj.jdbc.Driver

    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB # 例如，全局最大单个文件大小
            max-request-size: 10MB # 例如，全局最大请求大小
    # WebMvcConfigurer for serving static resources (if storing locally)
    # See below for configuration

#    sql:
#        init:
#            mode: always
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    # ???? H2???????
    # datasource:
    #   url: jdbc:h2:mem:travel_demo
    #   driver-class-name: org.h2.Driver
    # h2:
    #   console:
    #     enabled: true # ?? H2 ???
logging:
    level:
        org.springframework.jdbc.datasource.init: DEBUG


springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger.html


file:
    upload-dir: uploads/ # 例如，存储在项目根目录下的 uploads 文件夹
# Spring MVC Multipart Properties (全局配置)
